name: Bump Formula - ULID

on:
  push:
    tags:
      - 'v*'
    # paths:
    #   - 'ulid.rb'

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: cloudresty/homebrew-taps
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Bump formula
        run: brew bump-formula-pr --version ${{ github.ref_name }} ulid
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}