name: Bump Formula - Ulid

on:
  repository_dispatch:
    types: [ulid-release]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: cloudresty/homebrew-taps
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Bump formula
        id: bump
        run: |
          brew bump-formula-pr --version ${{ github.event.client_payload.ref }} ulid
          echo "::set-output name=output::$(brew bump-formula-pr --version ${{ github.event.client_payload.ref }} ulid)"
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}

      - name: Debug Output
        run: echo "${{ steps.bump.outputs.output }}"